name: yttx_video_room
description: A new Flutter project.
version: 0.0.1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  dio: ^3.0.10
  all_websocket:
    git: http://192.168.2.252:8888/yttx/yttx_websocket.git
